_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 5
                - 6
                - 7
                - 8
                - 35
                - 53
                - 54
                - 55
                - 105
            "2":
                - 5
                - 6
                - 7
                - 8
                - 35
                - 53
                - 54
                - 55
                - 105
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
                - 62
            "4": 3.11.11
            "5": 0.19.9
            "8":
                - 1
                - 2
                - 6
                - 12
            "12": 0.19.9
            "13": linux-x86_64
dataset:
    value: Titanic
framework:
    value: scikit-learn
models:
    value:
        - RandomForest
        - LogisticRegression
        - MLP
        - CatBoost
        - XGBoost
        - LightGBM
